language: julia
sudo: required
dist: trusty
julia:
  - nightly
  - 1.0
matrix:
  allow_failures:
    - julia: nightly
notifications:
  email: false
before_install:
  - sudo apt-get -qq update

script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --project --color=yes --check-bounds=yes -e 'import Pkg; Pkg.build(); Pkg.test("alg4opt_test"; coverage=true)'
after_success:
  - julia --project --color=yes -e 'import Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
