language: julia
julia:
  - nightly
  - 1.0
matrix:
  allow_failures:
    - julia: nightly
notifications:
  email: false
before_install:
  - sudo apt-get -qq update
coveralls: true
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --project --check-bounds=yes -e 'import Pkg; Pkg.clone(pwd()); Pkg.build(); Pkg.test("alg4opt_test"; coverage=true)'