language: julia
os:
  -linux
julia:
  - nightly
  - 1.0
matrix:
  allow_failures:
    - julia: nightly
notifications:
  email: false
before_install:
  - sudo apt-get -qq update
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --project --check-bounds=yes -e 'import Pkg; Pkg.build(); Pkg.test("alg4opt_test"; coverage=true)'
after_success:
  - julia --project -e 'using Pkg; cd(Pkg.dir("alg4opt_test")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'